\LoadClass{article}

\RequirePackage[utf8]{inputenc}
\RequirePackage[T5]{fontenc}
\RequirePackage[fontsize = 13pt]{scrextend}
\RequirePackage[paperheight = 29.7cm, paperwidth = 21cm, right = 2cm, left = 3cm, top = 2cm, bottom = 2.5cm, twoside]{geometry}
\RequirePackage{mathptmx}
\RequirePackage{graphicx}
\RequirePackage{float}
\RequirePackage{tikz}
\RequirePackage{indentfirst}
\RequirePackage{titlesec}
\RequirePackage[font = bf]{caption}
\RequirePackage{tabularx}
\RequirePackage{lipsum}
\RequirePackage[unicode]{hyperref}
\RequirePackage{colortbl}
\RequirePackage{forloop}
\RequirePackage{enumitem}